baseURL: 'https://mstva.github.io/'
languageCode: 'en-us'
title: 'mstva'
theme: 'hugo_papermod'

params:
  author: "Mustafa Abdallah"
  hideFooter: true
  ShowCodeCopyButtons: true
  DateFormat: "02 Jan 2006"

  profileMode:
    enabled: true
    title: "Mustafa Abdallah"
    subtitle: "Junior Python Backend Engineer"
    description: "As a backend engineer with 2 years of experience, 
    I have honed my skills working with Python, Django, Flask, PostgreSQL, Docker, AWS, Terraform, and CircleCI. 
    Since graduating from computer engineering school, 
    I have worked as a freelancer on Upwork and quickly achieved 
    Top-Rated Plus status with 100% job success in less than a year. 
    I have had the privilege of working with clients from around the globe, 
    including Ireland, Canada, and the United States. 
    By consistently delivering high-quality and professional work, 
    with excellent English communication and flexible time and timezone, 
    I have built a strong reputation for client satisfaction, 
    leading to long-term relationships that have lasted over a year. 
    I am excited to bring my expertise and dedication to your projects."
    imageUrl: "https://avatars.githubusercontent.com/u/20958970?v=4"
    imageTitle: mstva_img
    imageWidth: 120
    imageHeight: 120

  socialIcons:
    - name: twitter
      url: "https://twitter.com/MustafaAbdulluh"
    - name: github
      url: "https://github.com/mstva"
    - name: linkedin
      url: "https://linkedin.com/in/mustafaabdulluh"
    - name: upwork
      url: "https://www.upwork.com/freelancers/~01827d2d94f6d3cbd6"

permalinks:
  tech_writings: ':filename/'
  arabic_writings: ':filename/'
  projects: 'projects/:filename/'
  hire_me: ':filename/'

menu:
  main:
    - name: "tech_writings"
      weight: 1
      url: "tech_writings/"

    - name: "كتاباتي_بالعربية"
      weight: 2
      url: "arabic_writings/"

    - name: "projects"
      weight: 3
      url: "projects/"

    - name: "resume"
      weight: 4
      url: "resume/Backend_Engineer_Mustafa_Abdallah_Mohamed.pdf"

    - name: "hire_me"
      weight: 0
      url: "hire/"
